import type { CityNpcDef } from "@/features/types";

export const CITY_NPCS: CityNpcDef[] = [
  { kind: "npc", id: "lin-ran", name: "Lin Ran", nameCn: "林然", role: "现实拆解型职场妈妈", desc: "在工作、育儿与自我成长之间寻找可持续平衡。", dialogue: ["家庭不能依靠某一个人的长期牺牲运行。", "我会同时检查事实、感受、责任分配和可持续性。"], route: "/creator/lin-ran", actionLabel: "查看个人主页", debateAgentId: "lin-ran", color: 0xd48258, spriteFrame: 1, behavior: "patrol", points: [{ x: 190, y: 330 }, { x: 390, y: 340 }, { x: 300, y: 395 }] },
  { kind: "npc", id: "meng-yuxuan", name: "Meng Yuxuan", nameCn: "孟宇轩", role: "航空电子量化工程派", desc: "深耕航空电子、嵌入式与多模态 AI 落地。", dialogue: ["方案先量化、再分模块，最后进入真实工作流。", "安全、隐私、法律与学术诚信不可交换。"], route: "/creator/meng-yuxuan", actionLabel: "查看个人主页", debateAgentId: "meng-yuxuan", color: 0x4f7995, spriteFrame: 2, behavior: "patrol", points: [{ x: 480, y: 350 }, { x: 720, y: 332 }, { x: 620, y: 405 }] },
  { kind: "npc", id: "li-minghan", name: "Li Minghan", nameCn: "李明翰", role: "底层原理与证据链研究派", desc: "连接工程落地、计算机视觉和多模态 Agent。", dialogue: ["结论必须能追溯到定义、原始证据或可复现实验。", "先理解底层原理，再搭建完整技术链路。"], route: "/creator/li-minghan", actionLabel: "查看个人主页", debateAgentId: "li-minghan", color: 0x7b6c9c, spriteFrame: 3, behavior: "patrol", points: [{ x: 820, y: 330 }, { x: 980, y: 360 }, { x: 900, y: 400 }] },
  { kind: "npc", id: "zhangxuefeng", name: "Zhang Xuefeng", nameCn: "张雪峰", role: "教育观察员", desc: "从现实收益、就业倒推和社会筛选出发讨论选择。", dialogue: ["普通家庭做选择，方向比努力更要命。", "先把现实收益和就业出口算清楚，别只听口号。"], route: "/creator/zhangxuefeng", actionLabel: "查看人物档案", debateAgentId: "zhangxuefeng", color: 0xd39930, spriteFrame: 4, behavior: "patrol", points: [{ x: 180, y: 645 }, { x: 420, y: 650 }, { x: 320, y: 625 }] },
  { kind: "npc", id: "zhangyiming", name: "Zhang Yiming", nameCn: "张一鸣", role: "产品 / 平台", desc: "关注长期变量、信息效率和系统反馈。", dialogue: ["少装一点，多看系统到底在奖励什么。", "不要只看一次结果，要看反馈机制会把人推向哪里。"], route: "/creator/zhangyiming", actionLabel: "查看人物档案", debateAgentId: "zhangyiming", color: 0x5b9b66, spriteFrame: 5, behavior: "patrol", points: [{ x: 470, y: 650 }, { x: 740, y: 650 }, { x: 600, y: 615 }] },
  { kind: "npc", id: "musk", name: "Musk", nameCn: "马斯克", role: "科技冒险家", desc: "用第一性原理拆掉约束，偏爱高杠杆技术和大胆行动。", dialogue: ["先把问题压成成本、速度和系统瓶颈。", "如果约束只是习惯，不是物理定律，就应该重做。"], route: "/creator/musk", actionLabel: "查看人物档案", debateAgentId: "musk", color: 0x6f8794, spriteFrame: 6, behavior: "patrol", points: [{ x: 760, y: 650 }, { x: 980, y: 642 }, { x: 880, y: 615 }] },
  { kind: "npc", id: "claude", name: "Claude", nameCn: "Claude", role: "逻辑裁判", desc: "把争议拆成变量、假设和可验证边界。", dialogue: ["先把争议拆开，避免漂亮但空泛的结论。", "哪些条件成立，哪些证据会让判断改变？"], route: "/creator/claude", actionLabel: "查看人物档案", debateAgentId: "claude", color: 0x8b7ccf, spriteFrame: 7, behavior: "patrol", points: [{ x: 90, y: 390 }, { x: 190, y: 405 }, { x: 140, y: 620 }] },
  { kind: "npc", id: "doubao", name: "Doubao", nameCn: "豆包", role: "生活助理", desc: "先接住用户，再把复杂问题拆成可执行的小步骤。", dialogue: ["先别急着下结论，我们把最难受的那一块拆开。", "下一步不用很大，但要真的能做。"], route: "/creator/doubao", actionLabel: "查看人物档案", debateAgentId: "doubao", color: 0x3fac83, spriteFrame: 8, behavior: "tea", points: [{ x: 350, y: 465 }, { x: 620, y: 465 }, { x: 890, y: 465 }, { x: 650, y: 385 }] },
  { kind: "npc", id: "leijun", name: "Lei Jun", nameCn: "雷军", role: "硬件 / 发布会", desc: "把复杂技术讲成普通人可买、可用、可理解的价值。", dialogue: ["好产品不能只看参数，还得让普通人真的用得上。", "复杂技术最后要讲成一句真诚的话。"], route: "/creator/leijun", actionLabel: "查看人物档案", debateAgentId: "leijun", color: 0x4d8db7, spriteFrame: 9, behavior: "conversation-a", points: [{ x: 335, y: 355 }, { x: 585, y: 355 }] },
  { kind: "npc", id: "trump", name: "Trump", nameCn: "Trump", role: "气氛型辩手", desc: "用气势、胜负感和简单口号塑造鲜明立场。", dialogue: ["观点必须让人立刻知道你是赢还是输。", "太复杂的解释，传播上就是失败。"], route: "/creator/trump", actionLabel: "查看人物档案", debateAgentId: "trump", color: 0xe7aa45, spriteFrame: 10, behavior: "conversation-b", points: [{ x: 940, y: 355 }, { x: 695, y: 355 }] },
];

export const PATROL_NPCS = CITY_NPCS.filter((npc) => npc.behavior === "patrol");
export const TEA_STEWARD = CITY_NPCS.find((npc) => npc.behavior === "tea")!;
export const CONVERSATION_NPCS = CITY_NPCS.filter((npc) => npc.behavior.startsWith("conversation"));
