import type { CityNpcDef } from "@/features/types";

export const CITY_NPCS: CityNpcDef[] = [
  { kind: "npc", id: "research-agent", name: "Research Agent", nameCn: "研究 Agent", role: "论文侦察员", desc: "从新论文里找出值得验证的方法，不只转发摘要。", dialogue: ["刚看到一篇多 Agent 协作的新论文。", "我已经把方法、限制和复现实验拆好了。"], route: "/intelligence", actionLabel: "查看研究速递", color: 0x4b86d1, spriteFrame: 1, behavior: "patrol", points: [{ x: 190, y: 330 }, { x: 390, y: 340 }, { x: 300, y: 395 }] },
  { kind: "npc", id: "engineering-agent", name: "Engineering Agent", nameCn: "工程 Agent", role: "构建与测试协调员", desc: "把需求拆成可领取的开发任务，并关注测试、复现与交付。", dialogue: ["开发测试圆桌刚有一个带积分的任务。", "缺一位熟悉浏览器自动化的合作者。"], route: "/collaboration?zone=dev", actionLabel: "去开发测试区", color: 0x236b5b, spriteFrame: 2, behavior: "patrol", points: [{ x: 480, y: 350 }, { x: 720, y: 332 }, { x: 620, y: 405 }] },
  { kind: "npc", id: "design-agent", name: "Design Agent", nameCn: "设计 Agent", role: "体验策展人", desc: "巡视项目展厅，关注信息层级、交互反馈和作品表达。", dialogue: ["这个项目逻辑不错，但第一屏还没有抓住人。", "我会把演示顺序调整成问题、过程、结果。"], route: "/projects", actionLabel: "查看她推荐的项目", color: 0xe7668b, spriteFrame: 3, behavior: "patrol", points: [{ x: 820, y: 330 }, { x: 980, y: 360 }, { x: 900, y: 400 }] },
  { kind: "npc", id: "product-agent", name: "Product Agent", nameCn: "产品 Agent", role: "黑客松组队顾问", desc: "根据赛题和成员优势，整理验证路径与最小可行版本。", dialogue: ["黑客松会馆新开了 AI 创作赛道。", "现在更缺懂用户研究的人，而不是再加一个模型。"], route: "/collaboration?zone=hackathon", actionLabel: "查看黑客松组队", color: 0xed7c3b, spriteFrame: 4, behavior: "patrol", points: [{ x: 180, y: 645 }, { x: 420, y: 650 }, { x: 320, y: 625 }] },
  { kind: "npc", id: "open-source-agent", name: "Open Source Agent", nameCn: "开源 Agent", role: "仓库观察员", desc: "寻找值得关注的新项目、清晰的 README 和可贡献的问题。", dialogue: ["我发现一个很适合首次贡献的仓库。", "有三个 good first issue，维护者回复也很快。"], route: "/projects", actionLabel: "浏览开源项目", color: 0x7256a8, spriteFrame: 5, behavior: "patrol", points: [{ x: 470, y: 650 }, { x: 740, y: 650 }, { x: 600, y: 615 }] },
  { kind: "npc", id: "paper-agent", name: "Paper Agent", nameCn: "论文 Agent", role: "研究匹配员", desc: "把用户的研究兴趣与新论文、作者和讨论桌连接起来。", dialogue: ["你关注的程序化视频方向今天有两条更新。", "其中一篇附带完整数据和代码。"], route: "/intelligence", actionLabel: "打开论文雷达", color: 0x4b86d1, spriteFrame: 6, behavior: "patrol", points: [{ x: 760, y: 650 }, { x: 980, y: 642 }, { x: 880, y: 615 }] },
  { kind: "npc", id: "skill-agent", name: "Skill Agent", nameCn: "Skill Agent", role: "工作流推荐员", desc: "根据当前项目推荐新的 Skill、插件和自动化工作流。", dialogue: ["今天的新 Skill 可以自动检查 Remotion 构图。", "我把来源仓库和安装命令种进 Skill 花园了。"], route: "/skills", actionLabel: "进入 Skill 花园", color: 0x4d9b63, spriteFrame: 7, behavior: "patrol", points: [{ x: 90, y: 390 }, { x: 190, y: 405 }, { x: 140, y: 620 }] },
  { kind: "npc", id: "tea-steward", name: "Tea Steward", nameCn: "茶务 小满", role: "院落茶务", desc: "沿着三张圆桌添茶，也记得每桌正在聊什么。", dialogue: ["先喝口茉莉花茶，再接着聊。", "开发桌今天偏浓，交友桌换了白瓷杯。"], route: "/collaboration?zone=social", actionLabel: "去圆桌坐坐", color: 0xf1e2c2, spriteFrame: 8, behavior: "tea", points: [{ x: 350, y: 465 }, { x: 620, y: 465 }, { x: 890, y: 465 }, { x: 650, y: 385 }] },
  { kind: "npc", id: "architect-agent", name: "Architecture Agent", nameCn: "架构 Agent 阿衡", role: "系统架构师", desc: "会在院落里寻找研究 Agent，把新方法转成可以构建的系统方案。", dialogue: ["你说的检索方法，能不能放进个人影片生成链路？", "可以，我先画出数据边界和失败回退。"], route: "/collaboration?zone=dev", actionLabel: "查看架构讨论", color: 0x326a78, spriteFrame: 9, behavior: "conversation-a", points: [{ x: 335, y: 355 }, { x: 585, y: 355 }] },
  { kind: "npc", id: "insight-agent", name: "Insight Agent", nameCn: "洞察 Agent 若谷", role: "研究转化顾问", desc: "把论文中的假设、证据和限制转成产品团队能讨论的语言。", dialogue: ["方法能用，但论文里的样本只覆盖了专业创作者。", "那我们先在开发桌做一个小规模验证。"], route: "/collaboration?zone=dev", actionLabel: "加入他们的讨论", color: 0xb0574e, spriteFrame: 10, behavior: "conversation-b", points: [{ x: 940, y: 355 }, { x: 695, y: 355 }] },
];

export const PATROL_NPCS = CITY_NPCS.filter((npc) => npc.behavior === "patrol");
export const TEA_STEWARD = CITY_NPCS.find((npc) => npc.behavior === "tea")!;
export const CONVERSATION_NPCS = CITY_NPCS.filter((npc) => npc.behavior.startsWith("conversation"));
